![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [1]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print("POP")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [2]:
# TESTANDO
S = Stack()

In [3]:
S.print_stack()

[]


In [4]:
S.push(1)

PUSH 1


In [5]:
S.push(2)

PUSH 2


In [6]:
S.push(3)

PUSH 3


In [7]:
S.print_stack()

[1, 2, 3]


In [8]:
S.pop()

POP


3

In [9]:
S.pop()

POP


2

In [10]:
S.print_stack()

[1]


In [11]:
S.push(7)

PUSH 7


In [12]:
S.push(8)

PUSH 8


In [13]:
S.push(9)

PUSH 9


In [14]:
S.print_stack()

[1, 7, 8, 9]


In [15]:
print(S.is_empty())

False


### Segunda Implementação

In [17]:
import numpy as np

In [50]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            self.__valores[self.__topo] = 0
            self.__topo -= 1
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [51]:
pilha = Pilha(5)

In [52]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [53]:
pilha.ver_topo()

-1

In [54]:
pilha.empilhar(1)
pilha.ver_topo()

1

In [55]:
pilha.empilhar(1)
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)

In [56]:
pilha.imprime_pilha()

[1 1 2 3 4]


In [57]:
pilha.empilhar(6)

A pilha está cheia


In [58]:
pilha.ver_topo()

4

In [59]:
pilha.desempilhar()

In [60]:
pilha.ver_topo()

3

In [61]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

In [62]:
pilha.ver_topo()

1

In [63]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [64]:
pilha.desempilhar()

In [65]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [66]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
#### Exercício 1:

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [2]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [6]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  233


PUSH 1
PUSH 0
PUSH 0
PUSH 1
PUSH 0
PUSH 1
PUSH 1
PUSH 1
POP
POP
POP
POP
POP
POP
POP
POP
O valor 233 em binário é: 11101001


#### Exercício 2: Sistema de Desfazer e Refazer em um Editor de Texto
Implemente um sistema simples de "desfazer" e "refazer" operações em um editor de texto utilizando duas pilhas. Cada operação feita no texto (como adicionar ou remover caracteres) pode ser "desfeita" e, posteriormente, "refeita". Utilize duas pilhas: uma para armazenar as operações realizadas e outra para armazenar as operações desfeitas.

Descritivo do Problema:
- O sistema deve permitir realizar uma operação (inserir um caractere).
- Deve ser possível desfazer a última operação (usando uma pilha de desfazer).
- Após o desfazer, deve ser possível refazer a operação (usando uma pilha de refazer).
- Exibir o estado atual do texto.

In [ ]:
# Redefinindo a classe Stack (Pilha) 
# No método pop() foi adicionado uma checagem para garantir que o método não tente remover um item se a pilha estiver vazia
# No método peek() foi adicionado uma verificação para garantir que não cause erro de índice quando a pilha estiver vazia.
# Tanto nos métodos push() e pop() ocorria uma impressão (print) isso foi retirado para otimizar o processo.
# O atributo self.itens foi alterado para self.items (apenas estilo)
# Essa mesma classe erá utilizada neste exercício (2) e no próximo (3) E TAMBÉM NO EXERCÍCIO EXTRA

class Stack:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()

    def peek(self):
        return self.items[-1] if not self.is_empty() else None

    def size(self):
        return len(self.items)

In [ ]:
# Sistema de Desfazer e Refazer
class EditorTexto:
    def __init__(self):
        self.texto = []
        self.desfazer_pilha = Stack()  # Pilha de desfazer
        self.refazer_pilha = Stack()   # Pilha de refazer

    def inserir_caractere(self, caractere):
        self.texto.append(caractere)
        self.desfazer_pilha.push(caractere)
        self.refazer_pilha = Stack()  # Limpa a pilha de refazer
        print(f"Inserido: {caractere}")
        self.exibir_texto()

    def desfazer(self):
        if not self.desfazer_pilha.is_empty():
            ultimo_caractere = self.desfazer_pilha.pop()
            self.texto.pop()
            self.refazer_pilha.push(ultimo_caractere)
            print(f"Desfeito: {ultimo_caractere}")
        else:
            print("Nada para desfazer.")
        self.exibir_texto()

    def refazer(self):
        if not self.refazer_pilha.is_empty():
            caractere_refazer = self.refazer_pilha.pop()
            self.texto.append(caractere_refazer)
            self.desfazer_pilha.push(caractere_refazer)
            print(f"Refeito: {caractere_refazer}")
        else:
            print("Nada para refazer.")
        self.exibir_texto()

    def exibir_texto(self):
        print("Texto atual:", ''.join(self.texto))

In [ ]:
# Testando o sistema
editor = EditorTexto()
editor.inserir_caractere('A')
editor.inserir_caractere('B')
editor.inserir_caractere('C')
editor.desfazer()
editor.refazer()
editor.desfazer()
editor.desfazer()
editor.refazer()

#### Exercício 3: Controle de Desempenho de Pilotos de Corrida
Implemente um sistema de controle de desempenho de pilotos em uma corrida de karts, utilizando uma pilha. A cada volta, o sistema registra o tempo do piloto (em segundos) e permite desfazer o último tempo registrado (caso um erro de cronometragem tenha ocorrido). No final, o sistema exibe o tempo total acumulado das voltas.

Descritivo do Problema:
- O sistema deve permitir adicionar o tempo de uma volta à pilha.
- Deve ser possível desfazer o último tempo registrado.
- No final, exibir o tempo total acumulado das voltas registradas.

In [ ]:
# Definindo a classe Stack (Pilha)
class Stack:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()

    def size(self):
        return len(self.items)

    def total_time(self):
        return sum(self.items)

In [ ]:
# Sistema de Controle de Voltas
class ControleCorrida:
    def __init__(self):
        self.voltas = Stack()

    def registrar_volta(self, tempo):
        self.voltas.push(tempo)
        print(f"Volta registrada: {tempo} segundos")
        self.exibir_tempo_total()

    def desfazer_volta(self):
        if not self.voltas.is_empty():
            tempo_removido = self.voltas.pop()
            print(f"Tempo desfeito: {tempo_removido} segundos")
        else:
            print("Nenhuma volta para desfazer.")
        self.exibir_tempo_total()

    def exibir_tempo_total(self):
        tempo_total = self.voltas.total_time()
        print(f"Tempo total acumulado: {tempo_total} segundos")

In [ ]:
# Testando o sistema
corrida = ControleCorrida()
corrida.registrar_volta(58)
corrida.registrar_volta(62)
corrida.registrar_volta(60)
corrida.desfazer_volta()
corrida.registrar_volta(61)

#### Exercício EXTRA: Verificação de Expressões Matemáticas ((EXPLICADO EM AULA))
Implemente um verificador de expressões matemáticas que utiliza uma pilha para validar se os parênteses, colchetes e chaves estão corretamente balanceados. A função deve percorrer a expressão e usar uma pilha para verificar se cada abertura tem um fechamento correspondente.

Descritivo do Problema:
- O sistema deve receber uma expressão matemática que contenha parênteses (), colchetes [] e chaves {}.
- Deve verificar se os símbolos de abertura e fechamento estão balanceados.
- Retornar "Válida" se a expressão estiver balanceada e "Inválida" caso contrário.

In [ ]:
# Definindo a classe Stack (Pilha)
class Stack:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()

    def peek(self):
        return self.items[-1] if not self.is_empty() else None

In [ ]:
# Função para verificar se os parênteses estão balanceados
def verificar_expressao(expressao):
    pilha = Stack()
    pares = {'(': ')', '[': ']', '{': '}'}

    for char in expressao:
        if char in pares.keys():  # Se for um símbolo de abertura
            pilha.push(char)
        elif char in pares.values():  # Se for um símbolo de fechamento
            if pilha.is_empty() or pares[pilha.pop()] != char:
                return "Inválida"
    
    return "Válida" if pilha.is_empty() else "Inválida"

In [ ]:
# Testando a função
expressao1 = "{[()]}"
expressao2 = "{[(])}"
expressao3 = "{[()]}"

print(f"Expressão 1: {verificar_expressao(expressao1)}")  # Válida
print(f"Expressão 2: {verificar_expressao(expressao2)}")  # Inválida
print(f"Expressão 3: {verificar_expressao(expressao3)}")  # Válida

### Fim Aula 6