![Algoritmos e Estrutura de Dados II - Prof Piva](AED2_banner.jpg)

## Aula 6 - Pilhas

### Primeira Implementação

In [1]:
# Implementacao da classe Pilha
class Stack:
    # Inicia com uma pilha vazia
    def __init__(self):
        self.itens = []
    
    # Verifica se pilha esta vazia
    def is_empty(self):
        return self.itens == []
    
    # Adiciona elemento no topo (topo e o final da lista)
    def push(self, item):
        self.itens.append(item)
        print(f"PUSH {item}")

    # Remove elemento do topo (final da lista)
    def pop(self):
        print(f"POP {self.itens[-1]}")
        return self.itens.pop()
    
    # Obtem o elemento do topo (mas nao remove)
    def peek(self):
    # Em Python, indice -1 retorna ultimo elemento (topo)
        return self.itens[-1]
    
    # Retorna o numero de elementos da pilha
    def size(self):
        return len(self.itens)
    
    # Imprime pilha na tela
    def print_stack(self):
        print(self.itens)

In [2]:
# TESTANDO
s = Stack()

In [3]:
print(s)

In [4]:
s.print_stack()

[]


In [5]:
s.push(1)

PUSH 1


In [6]:
s.push("Fatec")

PUSH Fatec


In [7]:
s.push(7.5)

PUSH 7.5


In [8]:
s.print_stack()

[1, 'Fatec', 7.5]


In [9]:
a = s.pop()

POP 7.5


7.5

In [10]:
x = s.pop()

POP Fatec


In [11]:
print(x)

Fatec


In [12]:
s.print_stack()

[1]


In [13]:
s.push(7)

PUSH 7


In [14]:
s.push(8)

PUSH 8


In [15]:
s.push(9)

PUSH 9


In [17]:
s.print_stack()

[1, 7, 8, 9]


In [18]:
print(s.is_empty())

False


### Segunda Implementação

In [21]:
import numpy as np

In [22]:
class Pilha:
    def __init__(self, capacidade):
        self.__capacidade = capacidade
        self.__topo = -1
        self.__valores = np.zeros(self.__capacidade, dtype=int)

    def __pilha_cheia(self):
        if self.__topo == self.__capacidade - 1:
            return True
        else:
            return False
    
    def __pilha_vazia(self):
        if self.__topo == -1:
            return True
        else:
            return False
    
    def empilhar(self, valor):
        if self.__pilha_cheia():
            print('A pilha está cheia')
        else:
            self.__topo += 1
            self.__valores[self.__topo] = valor
    
    def desempilhar(self):
        if self.__pilha_vazia():
            print('A pilha está vazia')
        else:
            vd = self.__valores[self.__topo]
            self.__valores[self.__topo] = 0
            self.__topo -= 1
            return vd
    
    def ver_topo(self):
        if self.__topo != -1:
            return self.__valores[self.__topo]
        else:
            return -1
    
    # Imprime pilha na tela
    def imprime_pilha(self):
        print(self.__valores)

In [27]:
pilha = Pilha(5)

In [28]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [29]:
pilha.ver_topo()

-1

In [30]:
pilha.empilhar(1)
pilha.ver_topo()

np.int64(1)

In [31]:
pilha.empilhar(2)
pilha.empilhar(3)
pilha.empilhar(4)
pilha.empilhar(5)

In [32]:
pilha.imprime_pilha()

[1 2 3 4 5]


In [33]:
pilha.empilhar(6)

A pilha está cheia


In [34]:
pilha.ver_topo()

np.int64(5)

In [35]:
pilha.desempilhar()

np.int64(5)

In [36]:
pilha.ver_topo()

np.int64(4)

In [37]:
pilha.desempilhar()
pilha.desempilhar()
pilha.desempilhar()

np.int64(2)

In [38]:
pilha.ver_topo()

np.int64(1)

In [39]:
pilha.imprime_pilha()

[1 0 0 0 0]


In [40]:
pilha.desempilhar()

np.int64(1)

In [41]:
pilha.imprime_pilha()

[0 0 0 0 0]


In [42]:
pilha.desempilhar()

A pilha está vazia


# Vamos à Prática!
## Exercício

Utilização de pilhas para conversão de números inteiros em decimal para binário (método da divisão sucessiva por 2).

**Utilização do classe Stack..**

In [43]:
# Função que converte um número decimal para binário
def decimal_binario(numero):
 s = Stack()
 while numero > 0:
     resto = numero % 2
     s.push(resto)
     numero = numero // 2
 binario = ''
 while not s.is_empty():
     binario = binario + str(s.pop())
 return binario

### Testando!
233 --> binário

In [44]:
# TESTANDO
n = int(input('Entre com um número inteiro: '))
print(f"O valor {n} em binário é: {decimal_binario(n)}") 

Entre com um número inteiro:  352


PUSH 0
PUSH 0
PUSH 0
PUSH 0
PUSH 0
PUSH 1
PUSH 1
PUSH 0
PUSH 1
POP 1
POP 0
POP 1
POP 1
POP 0
POP 0
POP 0
POP 0
POP 0
O valor 352 em binário é: 101100000


### Fim Teoria Aula 6